# This workflow builds and publishes the 2PartsCut web application
# It creates a distributable package that can be used by others

name: Build and Publish 2PartsCut

on:
  push:
    branches: [ main ]
  release:
    types: [created]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN
permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          
      - name: Install dependencies
        run: npm install
        
      - name: Create build directory
        run: mkdir -p dist
        
      - name: Create .nojekyll file
        run: touch ./.nojekyll
        
      - name: Copy static files to dist
        run: |
          cp -r index.html privacy.html terms.html css js _headers .nojekyll dist/
          
      - name: Update _headers file for CORS
        run: |
          echo 'Cross-Origin-Opener-Policy: same-origin' > ./dist/_headers
          echo 'Cross-Origin-Embedder-Policy: require-corp' >> ./dist/_headers

  publish-package:
    needs: build
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
          
      - name: Install dependencies
        run: npm install
        
      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
